const fs = require('fs');
const path = require('path');
const { execSync } = require('child_process');

/**
 * VitePress Master - AI Agent Documentation Orchestrator
 * Action Router:
 * - sync: Sync sidebar and config
 * - create: Scaffold new doc
 * - audit: Check links and build health
 */

const args = process.argv.slice(2);
const action = args.includes('--action') ? args[args.indexOf('--action') + 1] : 'help';

async function main() {
  console.log(`[VitePress-Master] Initializing action: ${action}...`);

  switch (action) {
    case 'sync':
      await syncSidebar();
      break;
    case 'create':
      const title = args.includes('--title') ? args[args.indexOf('--title') + 1] : 'New Document';
      const docPath = args.includes('--path') ? args[args.indexOf('--path') + 1] : 'temp.md';
      await createDoc(title, docPath);
      break;
    case 'audit':
      await auditDocs();
      break;
    default:
      printHelp();
  }
}

async function syncSidebar() {
  console.log('Scanning docs directory to sync sidebar...');
  // TODO: Implement recursive directory walker and config.ts patcher
  console.log('Action "sync" scaffolded. (Feature pending logic implementation)');
}

async function createDoc(title, docPath) {
  const fullPath = path.join(process.cwd(), 'docs', docPath);
  const content = `---
title: ${title}
date: ${new Date().toISOString()}
---

# ${title}

Document generated by Xiaoxia VitePress-Master.
`;
  
  if (!fs.existsSync(path.dirname(fullPath))) {
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
  }
  
  fs.writeFileSync(fullPath, content);
  console.log(`Document created: ${docPath}`);
}

async function auditDocs() {
  console.log('Running documentation audit...');
  // TODO: Integrate markdown-link-check or vitepress build check
  console.log('Audit completed (dry-run).');
}

function printHelp() {
  console.log(`
Usage: node index.js --action <action> [options]

Actions:
  sync              Sync .vitepress/config.ts sidebar with filesystem
  create            Create a new doc from template
  audit             Check for broken links or build errors

Options:
  --title "Name"    Title for the new document
  --path "folder/file.md" Relative path in docs/
  `);
}

main().catch(err => {
  console.error(err);
  process.exit(1);
});
